### ISSUE TITLE
uECC_OPTIMIZATION_LEVEL 1 leads to errors

### ISSUE THREAD

**Issue by Sossenbinder** [kmackay/micro-ecc#111]
Hello,

I tried to set the uECC_OPTIMIZATION_LEVEL to 1, as mentioned in the uECC.h file in order to lower code size.

However, I am left with these errors:

     asm_avr.inc:879:5:  error: invalid lvalue in asm output 3

     __asm__ volatile (

     ^

and

       asm_avr.inc: In function 'uECC_vli_sub':
       asm_avr.inc:892:58: error: 'i' undeclared (first use in this function)

         : "+z" (r), "+x" (left), "+y" (right), [i] "+r" (i),

                                                          ^

Any idea how to fix this?

**Comment by kmackay** [comment]
Are you compiling with -O1 or higher?

**Comment by Sossenbinder** [comment]
I don't think so, I am currently using the Arduino IDE, and according to the config files no optimiziation flag is given. Is this necessary?

**Comment by kmackay** [comment]
-Os should work. I see there is an error.

**Comment by Sossenbinder** [comment]
Thanks. I can now compile without any errors.
