### ISSUE TITLE
not defined g_rng_function under asm_avr

### ISSUE THREAD

**Issue by LiWeiJie** [kmackay/micro-ecc#112]
hello,
     Recently, I try to deploy the micro-ecc to my atmel-studio project. But there are some errors occupies. One is that the uECC_generate_random_int() returns 0 caused by the declaration
 "static uECC_RNG_Function g_rng_function = 0;"  on the line 187 in "uECC.c",  so that failed to uECC_make_key() .
    I saw that the default_RNG_defined and g_rng_function only defined under "windows" or "Some POSIX-like system with /dev/urandom or /dev/random. ",  what should I do when it run under asm-avr?

**Comment by kmackay** [comment]
On embedded platforms, you need to define your own RNG function. There is an example in examples/ecc_test/ecc_test.ino
