### ISSUE TITLE
Trying to compile in IAR for Renesas RL78

### ISSUE THREAD

**Issue by djstkg** [kmackay/micro-ecc#119]
Hi,

I find your lib very nice, it´s simple and very understandable. I am generally trying to understand how ECC works with it and then use it further for my ideas.

I am trying to compile it as mentioned above, it is a 16bit uC. In your readme it says it supports 8, 32, 64 bits. Why is 16 not there? And where should I pay attention to with respect to that?

I see you have not implemented g_rng_function. For the sake of fast testing I did:

```
int g_rng_function(uint8_t * output, uint8_t numOfBits) {
  *output = 1;
  return 1;     /* on success 1, on error 0 */
}
```
But it stucks at the signing part of your example 

`            if (!uECC_sign(private, hash, sizeof(hash), sig, curves[c])) {`

or rather in the part:

```
    for (tries = 0; tries < uECC_RNG_MAX_TRIES; ++tries) {
        if (!g_rng_function((uint8_t *)random, num_words * uECC_WORD_SIZE)) {
            return 0;
	    }
        random[num_words - 1] &= mask >> ((bitcount_t)(num_words * uECC_WORD_SIZE * 8 - num_bits));
        if (!uECC_vli_isZero(random, num_words) &&
		        **_uECC_vli_cmp(top, random, num_words) == 1_**) {
            return 1;
        }
    }
```
because top < random always.

Could you pls propose some RNG function that would fit here nicely? Maybe one that you use.

Thanks

**Comment by kmackay** [comment]
In general you need to provide a RNG appropriate to your specific platform. Some options are:
 * Use environmental noise. There is an example of this in ecc_test.ino
 * Use timing noise from things like network events.
 * Use a hardware RNG.

I think 16 bit platforms should "work" as long as they support uint64_t, but they will be really slow without asm support.
