### ISSUE TITLE
ECDSA between micro-ecc and Java 

### ISSUE THREAD

**Issue by tijins** [kmackay/micro-ecc#12]
hello.

I signing a data on micro-ecc and verify with Java system(Android).
but verify result is any time "false"

what should I do?
please help.

**Comment by ricmoo** [comment]
I have built Objective-C wrappers for the older easy-ecc library, and regularly have GitHub issues opened against me regarding this... It is almost always the problem that you are using Bouncy Castle or some such Java library which encodes the signature (and keys, and whatnot) as ASN.1 DER encoded data, with random amounts of meta data encoded in the payload. Make sure you extract the correct portion of the data.
