### ISSUE TITLE
Bug Type: typedef int (*uECC_RNG_Function)(uint8_t *dest, unsigned size);

### ISSUE THREAD

**Issue by djstkg** [kmackay/micro-ecc#120]
Types don´t match:

```
...
int g_rng_function(uint8_t * output, uint8_t numOfBits) {
...
uECC_RNG_Function uECC_get_rng(void) {
    return g_rng_function;
}
```

`typedef int (*uECC_RNG_Function)(uint8_t *dest, unsigned size);`

should be

` typedef int (*uECC_RNG_Function)(uint8_t *dest, uint8_t size);`

**Comment by kmackay** [comment]
I think this is a bug in your code; I don't have any RNG function definition with 'uint8_t numOfBits' as the second arg.
