### ISSUE TITLE
Compiling on IAR for Amiqmicro Apollo2

### ISSUE THREAD

**Issue by saifabuhashish** [kmackay/micro-ecc#126]
Hello,

I am trying to use the library to test the performance of ECC on an Ambiqmicro apollo2. I downloaded the SDK and compiled the test_ecdh.c file, haven't added anything to the code. The code compiles with 0 warnings, however, when I run it in debug mode, it the function uECC_make_key fails after the first call. Any idea on what might be happening?

**Comment by kmackay** [comment]
Did you call uECC_set_rng()? There isn't a default RNG defined for your platform, so you'll need to provide one.
