### ISSUE TITLE
public key exchange

### ISSUE THREAD

**Issue by 22karthik** [kmackay/micro-ecc#132]
Hi 
I am not sure of syntax for public key or private key.The private and public key pair work well when it is generated by the algorithm itself.

But this not what I need,public key has to be exchanged between two machines.So I have designed the code with manual insertion of public key but the algorithm fails to work as required.So can you please let me know the syntax of the private or public key.

**Comment by Xiadalei** [comment]
You need to check the byteorder. 
By default, the alg use little endian to sign/verify/etc. (signature included, it's really easy to be ignored) when the majority of the cryto library use big endian. 
So you need to make sure the byteorder is the same in the two devices, that is public key/signature/private key/etc. Just make sure these big integer is aligned with same byteorder.
