### ISSUE TITLE
Library with binary curve (e.g. sect283r1) support?

### ISSUE THREAD

**Issue by zcode1** [kmackay/micro-ecc#140]
@kmackay, thank you for the great library - it has been very useful!

We have the need to verify a signature using a binary curve F(2^m) (e.g. sect283r1), but your library only supports prime curves.  Do you have any recommendations for a library similar to micro-ecc (small, open source, C) that supports ECDSA signature verification for this curve type?  

I have been looking at tiny-ecdh as a candidate, but it still has some errors in the ecdsa_verify() function.

**Comment by kmackay** [comment]
Sorry, I don't know of any specifically.
