### ISSUE TITLE
wrong public key generated for secp160r1

### ISSUE THREAD

**Issue by SurajMohammadShaik** [kmackay/micro-ecc#147]
I ran this algorithm and used the private and public key from the online tool to verify
tool link : http://www-cs-students.stanford.edu/~tjw/jsbn/ecdh.html
The public key generated by the tool does not match with the public key generated by your algorithm
I have verified all the parameters and they are same in the tool and your algorithm

NOTE: If you are seeing the tool convert the decimal values into hex and verify with secp160r1 standard parameters from http://www.secg.org/SEC2-Ver-1.0.pdf (page number 16)

**Comment by kmackay** [comment]
It may be some issue between converting whatever format this random JavaScript produces to the expected format for uECC (which is the standard big-endian format, without the leading 0x04 byte for points).
