### ISSUE TITLE
 Is 'muladd function' not supported in 32 bit

### ISSUE THREAD

**Issue by yimok** [kmackay/micro-ecc#156]
Hi, I am trying to use micro ecc on 32 bit platform.

However, the #define of the muladd function disables this.

#if !asm_mult || (uECC_SQUARE_FUNC && !asm_square) || \
    (uECC_SUPPORTS_secp256k1 && (uECC_OPTIMIZATION_LEVEL > 0) && \
        ((uECC_WORD_SIZE == 1) || (uECC_WORD_SIZE == 8)))
static void muladd(uECC_word_t a,
                   uECC_word_t b,
                   uECC_word_t *r0,
                   uECC_word_t *r1,
                   uECC_word_t *r2) {
#if uECC_WORD_SIZE == 8 && !SUPPORTS_INT128

Is it impossible to use muladd function on 32bit platform?

Thanks.

**Comment by kmackay** [comment]
It should be enabled and work if asm_mult is not defined for your platform.
