### ISSUE TITLE
C# binding or BouncyCastle interface code

### ISSUE THREAD

**Issue by kiryat8** [kmackay/micro-ecc#158]
I want to use the micro-ecc (secp256k1) code on our end unit to create a public key to exchange the C# server's in order to get a shared secret that can be used for AES encryption|decryption after the connection process. I will send the raw 64 public key by way of our proprietary protocol to the Server after receiving the Server's public key in the same way. This may not be the correct way to do so since I am a rookie.  I tried using the C# Bouncy Castle library but it expects the key to be transferred in DER format, I think, which is larger that our standard packet buffer size. I could not figure out how to convert the raw 64 byte public key received to any usable format. I then thought to create a C++ dll of the micro-ecc that I could call from C# but I do not know if that would be an efficient or scalable way on the PC. Can anyone be of any help? It would seem very useful for this to be implemented for many projects. I understand also that the new Nordic chips use the micro-ecc library but could not find any C# code.

**Comment by kmackay** [comment]
It should be straightforward to create a DLL that exports the desired uECC functions. It is quite fast on x86, so I expect that approach would work fine.

Regarding format conversion, the DER format is kind of complicated. I found a good page here: https://letsencrypt.org/docs/a-warm-welcome-to-asn1-and-der/

For just a public key, I generated a keypair and extracted the public key using openssl:
```
> openssl ecparam -name prime256v1 -genkey -noout -out key.pem
> openssl ec -in key.pem -pubout -out public.pem -conv_form uncompressed
```

We can then look at the public key, which is human readable:
```
> cat public.pem
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE71TDHwQejNTnpqcuSeux9Yu7YAHq
UI098Dp+uUO4Y4V1OmxIpTbnHm/dVEOWjT7fy98VKsq+cYykxDkZL44Q3w==
-----END PUBLIC KEY-----
```

The middle bit is just the base64-encoded DER format. We can base64-decode that to get the raw DER data. Here it is as a raw sequence of hex-encoded bytes:
```
3059301306072a8648ce3d020106082a
8648ce3d03010703420004ef54c31f04
1e8cd4e7a6a72e49ebb1f58bbb6001ea
508d3df03a7eb943b86385753a6c48a5
36e71e6fdd5443968d3edfcbdf152aca
be718ca4c439192f8e10df00
```

Then, by decoding the DER format, we can see the different parts.

First, we have a SEQUENCE of 0x59 bytes:
```
3059
```

The first item in the sequence is another SEQUENCE, of 0x13 (=19) bytes:
```
3013
```

The two entries in this sub-sequences are OBJECT IDENTIFIERs:
```
06072a8648ce3d0201 06082a8648ce3d030107
```
Then, back in the main sequence, the next entry is a BIT STRING of 0x42 bytes, with 0 unused bits:
```
034200
```

and the actual value of the bitstring is just the public key, prefixed with 0x04 to indicate that it is uncompressed:
```
04 ef54c31f041e8cd4e7a6a72e49ebb1f58bbb6001ea508d3df03a7eb943b86385753a6c48a536e71e6fdd5443968d3edfcbdf152acabe718ca4c439192f8e10df
```

So, if you took the last 64 bytes of that DER data, it would be the public key, ready to pass into uECC.
