### ISSUE TITLE
ppc asm implementation

### ISSUE THREAD

**Issue by gitroem** [kmackay/micro-ecc#16]
Hi Ken,

thanks for this great piece of software. 

At the moment I am trying to integrate the library into a ppc processor with e200 core. My first tests show, that it works! So YAY!!!

Still the performance could be better. On arm (Arduino Due) I can see, that the asm optimization reduce the time needed significantly. Do you know of any ppc asm optimization for your library?

Thanks,
gitroem

**Comment by kmackay** [comment]
You can write a PowerPC asm implementation pretty easily I think. The most important functions to implement are vli_add, vli_sub, and vli_mult.

I could try to implement it but I don't have any PowerPC machine to test with.
