### ISSUE TITLE
Secure scalar point multiplication is incorrect in rare occasions

### ISSUE THREAD

**Issue by pmvr** [kmackay/micro-ecc#167]
The algorithm, that is implemented in `uECC_compute_public_key`, is a Montgomery ladder with (X,Y)-only co-Z addition. It breaks when the point at infinity is reached.
Since the ephemeral key k is regularized to achieve a constant timing, the algorithm breaks for example for the elliptic curve secp256r1 when the scalar is 1, m-1 or m-2, where m is the order of the curve.
Thus, the implementation is functionally incorrect.

**Comment by kmackay** [comment]
Duplicate of #128
