### ISSUE TITLE
how to display the x value and y value of the public key?

### ISSUE THREAD

**Issue by PttCodingMan** [kmackay/micro-ecc#175]
As, title.

how to display the x value and y value of the public key?
Because I want to exchange key with other library.

Thanks for your reading.

**Comment by kmackay** [comment]
The x and y values are the first and second halves of the public key respectively. The canonical form to exchange with other libraries would be a buffer with byte 0x04, followed by the public key.

**Comment by PttCodingMan** [comment]
Thanks.

**Comment by PttCodingMan** [comment]
How can I restore the shared secret to the form of point (x and y)?
I want to compare the result of other libraries.

thanks.
