### ISSUE TITLE
secp256k1 not matching test vectors

### ISSUE THREAD

**Issue by dalbert2** [kmackay/micro-ecc#180]
I must be doing something wrong, but when I make/check keys using uECC with the secp256k1 curve, they don't match the results I get from Java's built-in crypto or popular libraries such as [BouncyCastle](https://www.bouncycastle.org/) or online testers such as https://gobittest.appspot.com/Address.  

I've attached a sample program that takes input from a file (specified on the command line) and calls uECC_make_key(), uECC_valid_public_key(), and uECC_compute_public_key() while reading inputs from specified file.  The uECC test program attached is built for Windows but can be rebuilt from the commandline (Makefile) or from within Netbeans
[uECC_test.zip](https://github.com/kmackay/micro-ecc/files/5610042/uECC_test.zip)
Sample output:
```
C:\Users\david\Subversion\NetBeans\uECC_test\dist\Debug\Cygwin-Windows>uECC_test makepublic private.bin
Private key: EB B2 C0 82 FD 77 27 89 0A 28 AC 82 F6 BD F9 7B
             AD 8D E9 F5 D7 C9 02 86 92 DE 1A 25 5C AD 3E 0F

Public key: F5 D0 89 B1 55 69 1B E9 A4 31 0C 61 74 10 78 E7
            22 58 96 0A F9 BE 65 E5 E5 DE 06 1D D8 C9 F7 83
            20 AF 7A 75 4B 18 F6 F1 77 E9 44 69 8A 83 94 03
            C3 29 92 E0 20 22 46 18 86 AB A1 78 9A 29 D8 CA
```
Note that the proper public key is: 04779DD197A5DF977ED2CF6CB31D82D43328B790DC6B3B7D4437A427BD5847DFCDE94B724A555B6D017BB7607C3E3281DAF5B1699D6EF4124975C9237B917D426F

As a reference (and hopefully ground truth), I have attached a java test program that uses both bouncycastle and java native crypto libraries and generates the correct public key both ways (see BC_test attached; original is here: https://github.com/java-crypto/Stackoverflow/tree/master/DervicePublicKeyFromPrivateKeyCurveSecp256k1)).  You can type `make run` to re-run the program - requires Java installed):
[BC_test.zip](https://github.com/kmackay/micro-ecc/files/5610034/BC_test.zip)
Output from BC_test:

```
$ make run
java -cp ".;./bcprov-ext-jdk15on-167.jar" BC_test
Generate ECPublicKey from PrivateKey (String) for curve secp256k1 (final)
Check keys with https://gobittest.appspot.com/Address

privatekey given : EBB2C082FD7727890A28AC82F6BDF97BAD8DE9F5D7C9028692DE1A255CAD3
E0F
publicKeyExpected: 04779DD197A5DF977ED2CF6CB31D82D43328B790DC6B3B7D4437A427BD584
7DFCDE94B724A555B6D017BB7607C3E3281DAF5B1699D6EF4124975C9237B917D426F

Generate PublicKey from PrivateKey with BouncyCastle
publicKeyExpected: 04779DD197A5DF977ED2CF6CB31D82D43328B790DC6B3B7D4437A427BD584
7DFCDE94B724A555B6D017BB7607C3E3281DAF5B1699D6EF4124975C9237B917D426F
publicKey BC     : 04779DD197A5DF977ED2CF6CB31D82D43328B790DC6B3B7D4437A427BD584
7DFCDE94B724A555B6D017BB7607C3E3281DAF5B1699D6EF4124975C9237B917D426F
publicKeys match : true

Generate PublicKey from PrivateKey with Java native routines
privateKey full  : 303E020100301006072A8648CE3D020106052B8104000A042730250201010
420EBB2C082FD7727890A28AC82F6BDF97BAD8DE9F5D7C9028692DE1A255CAD3E0F
ecPublicKeyFull  : 3056301006072A8648CE3D020106052B8104000A03420004779DD197A5DF9
77ED2CF6CB31D82D43328B790DC6B3B7D4437A427BD5847DFCDE94B724A555B6D017BB7607C3E328
1DAF5B1699D6EF4124975C9237B917D426F
ecPublicKeyHeader: 3056301006072A8648CE3D020106052B8104000A034200
ecPublicKeyKey   : 04779DD197A5DF977ED2CF6CB31D82D43328B790DC6B3B7D4437A427BD584
7DFCDE94B724A555B6D017BB7607C3E3281DAF5B1699D6EF4124975C9237B917D426F
publicKeyExpected: 04779DD197A5DF977ED2CF6CB31D82D43328B790DC6B3B7D4437A427BD584
7DFCDE94B724A555B6D017BB7607C3E3281DAF5B1699D6EF4124975C9237B917D426F
publicKeys match : true
```

Other references use this same key and get the same results as bouncycastle and Java:
https://stackoverflow.com/questions/61069182/derive-ec-public-key-from-private-key-string-in-native-java-for-curve-secp256k1

I realize I must be doing something wrong; any pointers would be appreciated.

**Comment by kmackay** [comment]
It looks like you have set uECC_VLI_NATIVE_LITTLE_ENDIAN=1, so you need to reverse the byte order of the private key. I recommend setting uECC_VLI_NATIVE_LITTLE_ENDIAN=0 for most use cases. I pasted your given private key into the public_key_test_vectors.c test as an example, and it produced your expected public key.

Also note the leading 0x04 of the public key is omitted by uECC (it is just the standard way of indicating an uncompressed public key).
