### ISSUE TITLE
support for secp384r1

### ISSUE THREAD

**Issue by mikevoyt** [kmackay/micro-ecc#25]
The web page at http://kmackay.ca/micro-ecc/ indicates secp384r1 is supported, and shows performance results for this, but it doesn't appear that the GitHub repo (nor the tarball) has implemented it.  Would it be possible to add support for secp384r1?

**Comment by kmackay** [comment]
That was an old version of micro-ecc with a slightly different API (and no AVR support). You can use it by checking out the "old" branch.
