### ISSUE TITLE
SP800-56 compliancy?

### ISSUE THREAD

**Issue by henris42** [kmackay/micro-ecc#27]
Hi,

Have you checked if the micro-ecc implementation is compliant with NIST SP800-56A?
http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Ar2.pdf

**Comment by kmackay** [comment]
My opinion:
The micro-ecc data representations are compliant with Appendix C. The rest of NIST-SP800 is not applicable to micro-ecc itself, but it applicable to users of micro-ecc. In particular:
 * The random number generation and nonce generation is compliant as long as you provide a cryptographic random number generator to uECC_set_rng().
 * The domain parameters are set to the standard parameters for the supported curves.
 * Key establishment is done in the normal fashion, which is compliant.
 * Key exchange, validation, and management are left up to the user.
