### ISSUE TITLE
Support of 128bit curves and easy-ecc

### ISSUE THREAD

**Issue by kleuter** [kmackay/micro-ecc#42]
1. easy-ecc supports secp128r1 but the project seems to be abandoned, do you plan to add support of this curve in micro-ecc? 

2. Small question about public key, why is it ECC_BYTES + 1 in easy-ecc
and uECC_BYTES*2 ins micro-ecc ?

Thanks in advance

**Comment by kmackay** [comment]
1. I don't plan to add support for secp128r1 in micro-ecc. The security level is too small, and the curve parameters are irritating to work with.

2. In easy-ecc the public keys were compressed by default. In micro-ecc, most functions take uncompressed public keys, and I have uECC_compress()/uECC_decompress() to compress/decompress public keys if desired.

**Comment by kleuter** [comment]
Thanks for the answer!
