### ISSUE TITLE
What's the difference between uECC_WORDS and uECC_N_WORDS

### ISSUE THREAD

**Issue by phoenix-frozen** [kmackay/micro-ecc#45]
Hi @kmackay ! Sorry about the unorthodox use of issues for this question.

I'm integrating uECC into my PhD project, on the CC2530 SoC. It's an 8051 processor, with a tiny stack, so I'm adjusting the way memory is used in uECC.

I'm trying to figure out what the difference between uECC_WORDS and uECC_N_WORDS is. Can you enlighten me?

**Comment by kmackay** [comment]
secp160r1 is annoying because the value of n is slightly larger than 2^160. So so represent n, you need an extra word.
