### ISSUE TITLE
Consider changing return code values

### ISSUE THREAD

**Issue by jbdatko** [kmackay/micro-ecc#57]
So this is a pedantic request, but, IMHO, it's more customary to return 0 to indicate success and not zero for an error. I was a bit surprised that this not the case. EXIT_SUCCESS, for example, is defined in C99 as 0.

If you don't want to change it, maybe define macros like ```#define uECC_SUCCESS 1```? Feel free to tell me to STFU, but I figured I'd at least bring this up.

**Comment by kmackay** [comment]
I'd prefer to leave it the way it is; the return values are boolean success/failure, so you can do 'if (!uECC_verify(...)) { /* handle verify failure */ }' (for example), which I like better.
