### ISSUE TITLE
Is it possible to support more curves?

### ISSUE THREAD

**Issue by SamuelLeijten** [kmackay/micro-ecc#61]
we were wondering if it's possible to support more curves? secp384r1 or secp521r1? we would be very thankful if you could support them, or comment out the places where they should be added.
Thank you very much.

**Comment by kmackay** [comment]
I don't have any plans to support more curves at the moment. You should be able to follow the existing code to add support for new curves. However it will be quite a lot of work to add those larger curves since you will need to add new fast asm for those integer sizes as well (if you want speed).
