### ISSUE TITLE
Many warnings like "discard const qualifier" and an error "previous declaration"

### ISSUE THREAD

**Issue by juliabory** [kmackay/micro-ecc#63]
Since the new checkin I get warnings and an error. I can fix it with compiler flag I think but I wanted you to know.

uECC.c:1242:29: warning: passing argument 1 of 'hash_context->init_hash' discards 'const' qualifier from pointer target type
...
uECC.h:299:5: note: previous declaration of 'uECC_sign_deterministic' was here

**Comment by kmackay** [comment]
OK. I will fix it when I get back from vacation.

**Comment by kmackay** [comment]
I can't reproduce the errors you mention. Perhaps your uECC.h is out of date somehow? In the latest version, hash_context->init_hash() takes a "const struct uECC_HashContext *context" as the first argument anyway, so this error shouldn't occur.

**Comment by juliabory** [comment]
OK no problem, maybe you are right. The project is running with the old version now.
