### ISSUE TITLE
Hardware acceleration on TI CC2538?

### ISSUE THREAD

**Issue by weiqj** [kmackay/micro-ecc#68]
TI CC2538 has hardware acceleration on ECC related operations. Is there any plan to implement that?

**Comment by kmackay** [comment]
I don't plan to personally, but if someone implements it, that would be great.

**Comment by vhnatyk** [comment]
do you have any idea or example how to implement hardware acceleration on capable MCU's - some have for example secp256k1 built in hw implementations, would be thankful for any info
