### ISSUE TITLE
Hello, I cannot run this programme, help!

### ISSUE THREAD

**Issue by muscularman** [kmackay/micro-ecc#78]
when I run it,  it will fail.
coz  
uECC_generate_random_int(uECC_word_t *random,
                                          const uECC_word_t *top,
                                          wordcount_t num_words) 
return 0
However, it refers to g_rng_function
and
#if default_RNG_defined
static uECC_RNG_Function g_rng_function = &default_RNG;
#else 
static uECC_RNG_Function g_rng_function = 0;
#endif

ECC Test begin:
Testing 256 random private key pairs
0
uECC_make_key() failed

I find that in platform-specific

static int default_RNG(uint8_t *dest, unsigned size) {
    HCRYPTPROV prov;
    if (!CryptAcquireContext(&prov, NULL, NULL, PROV_RSA_FULL, CRYPT_VERIFYCONTEXT)) {
        return 0;
    }

    CryptGenRandom(prov, size, (BYTE *)dest);
    CryptReleaseContext(prov, 0);
    return 1;
}

How to use this function successfully ?  thanks very much

**Comment by kmackay** [comment]
If your platform is not known by uECC (ie, if you are not running on Windows or some POSIXy system), then you need to define your own RNG function and register it by calling uECC_set_rng(). See the documentation comments for uECC_RNG_Function and uECC_set_rng() in uECC.h.
