### ISSUE TITLE
Use HMAC

### ISSUE THREAD

**Issue by mathDv** [kmackay/micro-ecc#84]
Hi. First, congrats for your work.
I'm looking for a implementation in C of HMAC. It is possible to use in micro ecc ?
Thanks in advance.

**Comment by kmackay** [comment]
micro-ecc has an implementation of HMAC which you are free to use. You need to supply the hash function though (eg SHA256). One implementation of SHA256 can be found here: http://sources.freebsd.org/RELENG_8/src/sys/crypto/sha2/sha2.c <http://sources.freebsd.org/RELENG_8/src/sys/crypto/sha2/sha2.c>

See my test/test_ecdsa_deterministic.c.example to see how I wired up the SHA256 code to the micro-ecc HMAC. The actual HMAC implementation is in uECC.c; see HMAC_init(), HMAC_update(), and HMAC_finish().

**Comment by mathDv** [comment]
Hi. 
I could make the code run with this hash implementation (https://github.com/B-Con/crypto-algorithms).
Very nice, Thanks for the help..
