### ISSUE TITLE
num_n_bits for curve_secp160r1

### ISSUE THREAD

**Issue by JamesTCurran** [kmackay/micro-ecc#86]
Hello, 

perhaps I am mistaken, but I have had trouble with extracting private/public key size (in bytes) via the API for the secp160r1 curve. It seems that the function:
   int uECC_curve_private_key_size(uECC_Curve curve);
returns one byte larger than it should.  

I am begining to think that the source of the problem is the initialization of the variable: 
   num_n_bits 
at line 141 of  
   curve-specific.inc
where it is initialized to 161. Having changed this to 160, it seems to work fine, and the related sign/verify code seems to be ok.

Is there some special reason it was initialzied to 161, or was this a bug? Should it be 160?

Cheers,
James

**Comment by kmackay** [comment]
161 is the correct value, since the order of secp160r1 is > 2^160. See the comment for uECC_make_key().
