### ISSUE TITLE
Cannot verify signature with openssl

### ISSUE THREAD

**Issue by jbessow** [kmackay/micro-ecc#90]
I'm using key pairs secp256r1 generated with openssl to sign a SHA-256 hash with uECC_sign. However, when I try to verify the signature generated by micro-ECC with openssl I always get "Error Verifying Data".

Here are the private key and hash I'm using to sign:
uint8_t private_key[] = {0xd9, 0xcf, 0x8c, 0xb1, 0x87, 0x89, 0x6b, 0x48, 0x60, 0x48, 0x88, 0x77, 0x4d, 0xf0, 0xac, 0xae, 0xc6, 0x49, 0xf2, 0xd6, 0x63, 0x0c, 0xba, 0xb3, 0x17, 0x20, 0x9e, 0x2e, 0xef, 0xec, 0x2c, 0x7c};

uint8_t hash_sha256[] = {0x45, 0x54, 0x81, 0x3e, 0x91, 0xf3, 0xd5, 0xbe, 0x79, 0x0c, 0x7c, 0x60, 0x8f, 0x80, 0xb2, 0xb0, 0x0f, 0x3e, 0xa7, 0x75, 0x12, 0xd4, 0x90, 0x39, 0xe9, 0xe3, 0xdc, 0x45, 0xf8, 0x9e, 0x2f, 0x01};

The signature generated by uECC_sign:
8f61bd7593b1c2ae43772bd90b7156c85744d556efe73854bc5d74c45187966e2236f7649b8a6f468e3bb93e0757367383505c221e7039ff0a4060a91778d5a6

To verify with openssl command line I put the DER headers:
304402208f61bd7593b1c2ae43772bd90b7156c85744d556efe73854bc5d74c45187966e02202236f7649b8a6f468e3bb93e0757367383505c221e7039ff0a4060a91778d5a6

Public key in ASN-1 base64:
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOPMtv4VbmCIitOM+wRkAlhLQYK0T
6DniWR6xK6M8Bn/gGoJYesl8tYGO42+HHm5Hg/fbV2LQ1bKkk4IQGaQhKw==
-----END PUBLIC KEY-----

I'm compiling with default micro-ECC options:
    #define uECC_OPTIMIZATION_LEVEL 2
    #define uECC_SQUARE_FUNC 0
    #define uECC_VLI_NATIVE_LITTLE_ENDIAN 0
    #define uECC_ENABLE_VLI_API 0

So, is it possible to reach what I'm trying to do?

**Comment by kmackay** [comment]
Yes, it should work. uECC_sign() generates a standard signature. Potentially you aren't converting the r and s values to a format that OpenSSL recognizes?

I found this link that may be helpful: http://stackoverflow.com/questions/17084114/convert-raw-format-ecdsa-sha384-csr-signature-into-asn1-format
