### ISSUE TITLE
Possibility to split up calculations?

### ISSUE THREAD

**Issue by evertvr** [kmackay/micro-ecc#98]
First of all, thanks for this great library!

In my application, I find that the ECC calculation takes a long consecutive time to finish, which is logical, but is there a way to split up the calculations, so that my other tasks also have time to execute (I'm not using a preemptive scheduler). Could I, for instance "feed" data or intermediary results, or is there another more elegant way?

Thanks in advance!

**Comment by kmackay** [comment]
It is technically possible; you could for example split up the main loop
(the for() loop doing XYcZ_add and XYc_addC)  in EccPoint_mult() into
several steps.
